@server = http://127.0.0.1:16379

### 创建索引
### schema.fields.type: 0-Text;1-Numeric;2-Geo;3-Tag
POST  {{server}}/indexes/test
Content-Type: application/json

{
    "schema": {
        "fields": [
            {
                "name": "title",
                "type": "Text",
                "sortable": true
            },
            {
                "name": "body",
                "type": "Text",
                "sortable": false
            },
            {
                "name": "data",
                "type": "Numeric",
                "sortable": true
            }
        ]
    },
    "index_definition": {
        "index_on": "HASH",
        "prefix": [
            "test:"
        ],
        "async": false
    }
}

### 查询所有索引（名称列表）
GET {{server}}/indexes

### 查询索引信息
GET {{server}}/indexes/test

### 删除索引
DELETE {{server}}/indexes/test

### 根据ID获取文档
GET {{server}}/docs/test:1

### 批量创建文档
POST {{server}}/docs
Content-Type: application/json

[
    {
        "id": "test:0",
        "properties": {
            "date": 0,
            "title": "this_is_title"
        }
    },
    {
        "id": "test:1",
        "properties": {
            "date": 1,
            "title": "this is title"
        }
    },
    {
        "id": "test:2",
        "properties": {
            "date": 2,
            "title": "this-is-title"
        }
    },
    {
        "id": "test:3",
        "properties": {
            "date": 3,
            "title": "this\\ is\\ title"
        }
    },
    {
        "id": "test:4",
        "properties": {
            "date": 4,
            "title": "this\\-is\\-title"
        }
    }
]


### 删除文档
DELETE  {{server}}/docs/test:0
Content-Type: application/json


### 批量删除文档
DELETE  {{server}}/docs
Content-Type: application/json

[
    "test:0","test:1"
]


### 查询文档[GET]
GET  {{server}}/search/test?raw=*&limit=100&offset=0
Content-Type: application/json


### 查询文档[POST]
POST {{server}}/search/test
Content-Type: application/json

{
    "raw": "@title:this_is_title",
    "paging": {
        "offset": 0,
        "num": 10
    },
    "flags": 0,
    "slop": 0,
    "filters": null,
    "in_keys": null,
    "in_fields": null,
    "return_fields": null,
    "language": "",
    "expander": "",
    "scorer": "",
    "payload": null,
    "sort_by": null,
    "highlight_opts": null,
    "summarize_opts": null
}

### 获取redisearch索引列表
GET {{server}}/indexes

### 查看索引结构
GET {{server}}/indexes/prometheus-alert

### 使用redisearch搜索语句进行搜索
GET {{server}}/indexes/prometheus-alert/search?raw=@alertname:cpu*

### 修改值,上面搜索后的DOC有ID,key放的就是id
PUT {{server}}/docs

[
    {
        "id": "prometheus:alert:b8d59a88adc45c8b",
        "properties": {
            "test_key":"value1"
        }
    }
]

### 获取对应DOCID的值
GET {{server}}/documents/prometheus:alert:b8d59a88adc45c8b
